/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Unidad1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Unidad1
     */
    public Vista_Unidad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarUNIDAD1 = new javax.swing.JProgressBar();
        jButtonFINALIZARUNIDAD1 = new javax.swing.JButton();
        jButtonLECCIONSALUDOS = new javax.swing.JButton();
        jButtonLECCIONFONOLOGIA = new javax.swing.JButton();
        jButtonLECCIONPRONOMBRES = new javax.swing.JButton();
        jButtonACTIIVIDAD1 = new javax.swing.JButton();
        jButtonEVALUACION = new javax.swing.JButton();
        jButtonACTIVIDAD2 = new javax.swing.JButton();
        jButtonREINICIARU1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBarUNIDAD1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBarUNIDAD1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jProgressBarUNIDAD1.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarUNIDAD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jProgressBarUNIDAD1.setStringPainted(true);
        add(jProgressBarUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 260, 30));

        jButtonFINALIZARUNIDAD1.setText("FINALIZAR");
        add(jButtonFINALIZARUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 200, 40));

        jButtonLECCIONSALUDOS.setText("SALUDOS");
        add(jButtonLECCIONSALUDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jButtonLECCIONFONOLOGIA.setText("FONOLOGIA");
        add(jButtonLECCIONFONOLOGIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jButtonLECCIONPRONOMBRES.setText("PRONOMBRES");
        add(jButtonLECCIONPRONOMBRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jButtonACTIIVIDAD1.setText("ACTIVIDAD 1");
        add(jButtonACTIIVIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        jButtonEVALUACION.setText("EVALUACION 1");
        add(jButtonEVALUACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        jButtonACTIVIDAD2.setText("ACTIVIDAD 2");
        jButtonACTIVIDAD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACTIVIDAD2ActionPerformed(evt);
            }
        });
        add(jButtonACTIVIDAD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jButtonREINICIARU1.setText("Reiniciar");
        add(jButtonREINICIARU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 100, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSinPixel.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1190, 660));
        Fondo.setMinimumSize(new java.awt.Dimension(1190, 660));
        Fondo.setPreferredSize(new java.awt.Dimension(1190, 660));
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonACTIVIDAD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACTIVIDAD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTIVIDAD2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JButton jButtonACTIIVIDAD1;
    public javax.swing.JButton jButtonACTIVIDAD2;
    public javax.swing.JButton jButtonEVALUACION;
    public javax.swing.JButton jButtonFINALIZARUNIDAD1;
    public javax.swing.JButton jButtonLECCIONFONOLOGIA;
    public javax.swing.JButton jButtonLECCIONPRONOMBRES;
    public javax.swing.JButton jButtonLECCIONSALUDOS;
    public javax.swing.JButton jButtonREINICIARU1;
    public javax.swing.JProgressBar jProgressBarUNIDAD1;
    // End of variables declaration//GEN-END:variables
}
