/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_PanelUnidades extends javax.swing.JPanel {

    /**
     * Creates new form PanelUnidades
     */
    public Vista_PanelUnidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVistas = new javax.swing.JPanel();
        jLabelUNIDAD4 = new javax.swing.JLabel();
        jLabelUNIDAD3 = new javax.swing.JLabel();
        jLabelUNIDAD2 = new javax.swing.JLabel();
        jLabelUNIDAD1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));

        PanelVistas.setBackground(new java.awt.Color(255, 255, 255));
        PanelVistas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUNIDAD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidad4_bounce_suave.gif"))); // NOI18N
        PanelVistas.add(jLabelUNIDAD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, 180));

        jLabelUNIDAD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidad3_bounce_suave.gif"))); // NOI18N
        PanelVistas.add(jLabelUNIDAD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, 170));

        jLabelUNIDAD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidad2_bounce_suave.gif"))); // NOI18N
        PanelVistas.add(jLabelUNIDAD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, 170));

        jLabelUNIDAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidad1_bounce_suave.gif"))); // NOI18N
        PanelVistas.add(jLabelUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapa_redimensionado.png"))); // NOI18N
        PanelVistas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelVistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVistas;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabelUNIDAD1;
    public javax.swing.JLabel jLabelUNIDAD2;
    public javax.swing.JLabel jLabelUNIDAD3;
    public javax.swing.JLabel jLabelUNIDAD4;
    // End of variables declaration//GEN-END:variables
}
